import "./globals.css";
import { unlock, inter, poppins } from "./utils/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter} ${unlock} ${poppins}`}>{children}</body>
    </html>
  );
}
